# Generated by Django 5.2 on 2025-07-28 06:21

import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درگاه')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('mellat', 'ملت'), ('parsian', 'پارسیان'), ('saman', 'سامان'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع درگاه')),
                ('merchant_id', models.CharField(max_length=200, verbose_name='شناسه پذیرنده')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='کلید API')),
                ('zp_api_request', models.URLField(blank=True, verbose_name='آدرس درخواست')),
                ('zp_api_verify', models.URLField(blank=True, verbose_name='آدرس تایید')),
                ('zp_api_startpay', models.URLField(blank=True, verbose_name='آدرس شروع پرداخت')),
                ('callback_url', models.URLField(verbose_name='آدرس بازگشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='محیط تست')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12, verbose_name='حداقل مبلغ')),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('50000000'), max_digits=12, verbose_name='حداکثر مبلغ')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='درصد کمیسیون')),
                ('fixed_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='کمیسیون ثابت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='کد Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('card_pan', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('callback_url', models.URLField(blank=True, verbose_name='آدرس بازگشت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('completed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway', verbose_name='درگاه پرداخت')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='wallet.transaction', verbose_name='تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('request', 'درخواست'), ('callback', 'بازگشت'), ('verify', 'تایید'), ('error', 'خطا')], max_length=20, verbose_name='نوع لاگ')),
                ('message', models.TextField(verbose_name='پیام')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.paymentrequest', verbose_name='درخواست پرداخت')),
            ],
            options={
                'verbose_name': 'لاگ پرداخت',
                'verbose_name_plural': 'لاگ\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['authority'], name='payments_pa_authori_a646dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status'], name='payments_pa_status_363ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a76cc7_idx'),
        ),
    ]
