# Generated by Django 5.2 on 2025-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='max_amount',
            field=models.IntegerField(default=50000000, verbose_name='حداکثر مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='min_amount',
            field=models.IntegerField(default=1000, verbose_name='حداقل مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
    ]
