version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=dr_turn.settings_production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DB_HOST=services.irn2.chabokan.net
      - DB_NAME=drhmd302_marisa
      - DB_USER=drhmd302_marisa
      - DB
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=drhmd302_marisa
      - MYSQL_USER=drhmd302_marisa
      - MYSQL_PASSWORD=ts18dvorFu23
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_dr_turn.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data: 