# Generated by Django 5.2 on 2025-05-24 20:09

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('doctors', '0007_alter_doctor_created_at_alter_doctor_updated_at_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع تخفیف')),
                ('type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed_amount', 'مبلغ ثابت'), ('buy_one_get_one', 'یکی بخر یکی بگیر')], max_length=20, verbose_name='نوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوع تخفیف',
                'verbose_name_plural': 'انواع تخفیف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ثابت تخفیف')),
                ('applicable_to', models.CharField(choices=[('all', 'همه خدمات'), ('doctor', 'پزشک خاص'), ('specialization', 'تخصص خاص'), ('clinic', 'کلینیک خاص'), ('first_time', 'بیماران جدید'), ('returning', 'بیماران قدیمی')], max_length=20, verbose_name='قابل اعمال برای')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر مبلغ تخفیف')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده کل')),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده هر کاربر')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('expired', 'منقضی شده'), ('used_up', 'استفاده شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('clinics', models.ManyToManyField(blank=True, to='clinics.clinic', verbose_name='کلینیک\u200cها')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('doctors', models.ManyToManyField(blank=True, to='doctors.doctor', verbose_name='پزشکان')),
                ('specializations', models.ManyToManyField(blank=True, to='doctors.specialization', verbose_name='تخصص\u200cها')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discounttype', verbose_name='نوع تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_codes', to='discounts.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AutomaticDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('min_appointments_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل تعداد نوبت')),
                ('is_first_appointment', models.BooleanField(default=False, verbose_name='اولین نوبت')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='آخر هفته')),
                ('specific_days', models.CharField(blank=True, max_length=20, verbose_name='روزهای خاص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف خودکار',
                'verbose_name_plural': 'تخفیفات خودکار',
            },
        ),
        migrations.CreateModel(
            name='DiscountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', django_jalali.db.models.jDateField(verbose_name='شروع دوره')),
                ('period_end', django_jalali.db.models.jDateField(verbose_name='پایان دوره')),
                ('total_usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کل استفاده')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل تخفیف')),
                ('total_revenue_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تأثیر بر درآمد')),
                ('generated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ تولید گزارش')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='discounts.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'گزارش تخفیف',
                'verbose_name_plural': 'گزارش\u200cهای تخفیف',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ اصلی')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ نهایی')),
                ('used_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.couponcode', verbose_name='کد تخفیف')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount', verbose_name='تخفیف')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='reservations.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'ordering': ['-used_at'],
            },
        ),
    ]
