# Generated by Django 5.2 on 2025-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='max_free_appointments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر نوبت\u200cهای رایگان'),
        ),
    ]
