# Generated by Django 5.2 on 2025-07-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('doctors', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AddField(
            model_name='discount',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='doctors.doctor', verbose_name='پزشکان'),
        ),
        migrations.AddField(
            model_name='discount',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='doctors.specialization', verbose_name='تخصص\u200cها'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_codes', to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='discount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='discountreport',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discounttype', verbose_name='نوع تخفیف'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.couponcode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='reservations.reservation', verbose_name='رزرو'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
