# Generated by Django 5.2 on 2025-05-07 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تخصص')),
            ],
            options={
                'verbose_name': 'تخصص کلینیک',
                'verbose_name_plural': 'تخصص\u200cهای کلینیک',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('view_count', models.PositiveIntegerField(default=88, verbose_name='تعداد بازدید')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinics', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'کلینیک',
                'verbose_name_plural': 'کلینیک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ClinicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('recommendation', models.CharField(blank=True, choices=[('توصیه نمیکنم', 'توصیه نمیکنم'), ('توصیه میکنم', 'توصیه میکنم')], default=('توصیه میکنم', 'توصیه میکنم'), max_length=25, null=True, verbose_name='توصیه')),
                ('rate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clinics.clinic', verbose_name='کلینیک')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ClinicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic_gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinics.clinic', verbose_name='کلینیک')),
            ],
            options={
                'verbose_name': 'گالری کلینیک',
                'verbose_name_plural': 'گالری\u200cهای کلینیک',
            },
        ),
    ]
