# Generated by Django 5.1.6 on 2025-04-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلینیک')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کلینیک',
                'verbose_name_plural': 'کلینیک ها',
            },
        ),
        migrations.CreateModel(
            name='ClinicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinics/gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'تصویر کلینیک',
                'verbose_name_plural': 'گالری تصاویر کلینیک',
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'تخصص کلینیک',
                'verbose_name_plural': 'تخصص های کلینیک',
            },
        ),
    ]
