# Generated by Django 5.2 on 2025-05-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicspecialty',
            name='Doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_doctors', to='doctors.doctor', verbose_name='پزشکان'),
        ),
        migrations.AddField(
            model_name='clinicspecialty',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='clinics.clinic', verbose_name='کلینیک'),
        ),
    ]
