# Generated by Django 5.2 on 2025-04-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('rate', models.SmallIntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clinics.clinic', verbose_name='کلینیک')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
    ]
