# Generated by Django 5.2 on 2025-07-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinics', to=settings.AUTH_USER_MODEL, verbose_name='مدیر'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clinics.clinic', verbose_name='کلینیک'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='clinicgallery',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clinics.clinic', verbose_name='کلینیک'),
        ),
        migrations.AddField(
            model_name='clinicspecialty',
            name='Doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_doctors', to='doctors.doctor', verbose_name='پزشکان'),
        ),
        migrations.AddField(
            model_name='clinicspecialty',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='clinics.clinic', verbose_name='کلینیک'),
        ),
    ]
