# Generated by Django 5.2 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_comment',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Not recommended', 'توصیه نمیکنم'), ('Recommended', 'توصیه میکنم')], default=('Recommended', 'توصیه میکنم'), max_length=25, null=True, verbose_name='توصیه'),
        ),
    ]
