# Generated by Django 5.2 on 2025-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
