# Generated by Django 5.2 on 2025-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
