# Generated by Django 5.2 on 2025-04-30 12:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_comment_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل'),
        ),
        migrations.CreateModel(
            name='ClinicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('recommendation', models.CharField(blank=True, choices=[('توصیه نمیکنم', 'Not recommended'), (' توصیه میکنم', 'Recommended')], default=(' توصیه میکنم', 'Recommended'), max_length=25, null=True, verbose_name='توصیه')),
                ('rate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clinics.clinic', verbose_name='کلینیک')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
        migrations.DeleteModel(
            name='Clinic_Comment',
        ),
    ]
