# Generated by Django 5.2 on 2025-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_email_cliniccomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniccomment',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('توصیه نمیکنم', 'توصیه نمیکنم'), ('توصیه میکنم', 'توصیه میکنم')], default=('توصیه میکنم', 'توصیه میکنم'), max_length=25, null=True, verbose_name='توصیه'),
        ),
        migrations.AlterField(
            model_name='clinicspecialty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام تخصص'),
        ),
    ]
