# Generated by Django 5.2 on 2025-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_alter_cliniccomment_recommendation_and_more'),
        ('doctors', '0003_alter_city_options_remove_doctor_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicspecialty',
            name='Doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_doctors', to='doctors.doctor', verbose_name='پزشکان'),
        ),
    ]
