# Generated by Django 5.2 on 2025-04-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinicspecialty_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicspecialty',
            name='description',
        ),
    ]
