# Generated by Django 5.2 on 2025-05-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_remove_clinicspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='view_count',
            field=models.PositiveIntegerField(default=88, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='cliniccomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
