# Generated by Django 5.2 on 2025-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='واتساپ')),
                ('telegram', models.CharField(max_length=100, verbose_name='تلگرام')),
                ('instagram', models.CharField(max_length=100, verbose_name='اینستاگرام')),
                ('eitaa', models.CharField(max_length=100, verbose_name='ایتا')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام کاربران',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=65, verbose_name='اعلامیه')),
                ('published', models.BooleanField(default=False, verbose_name='نمایش داده شود')),
            ],
            options={
                'verbose_name': 'اعلامیه',
                'verbose_name_plural': 'اعلامیه ها',
            },
        ),
    ]
