# Generated by Django 5.2 on 2025-05-26 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Chat Status',
                'verbose_name_plural': 'Admin Chat Statuses',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=65, null=True, verbose_name='اعلامیه')),
                ('published', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمایش داده شود')),
            ],
            options={
                'verbose_name': 'اعلامیه',
                'verbose_name_plural': 'اعلامیه ها',
            },
        ),
        migrations.CreateModel(
            name='SupportChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Customer Support Chat', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if chat room is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last message sent in the chat')),
                ('admin', models.ForeignKey(default=1, help_text='Assigned admin (default: admin with ID 1)', on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer who initiated the chat (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='about_us.supportchatroom')),
                ('sender', models.ForeignKey(blank=True, help_text='Message sender; null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddIndex(
            model_name='supportchatroom',
            index=models.Index(fields=['customer', 'is_active'], name='about_us_su_custome_3f4ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchatroom',
            index=models.Index(fields=['admin', 'is_active'], name='about_us_su_admin_i_25cd60_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='about_us_su_chat_ro_f46e1f_idx'),
        ),
    ]
