# Generated by Django 5.2 on 2025-05-26 19:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_adminchatstatus_announcement_supportchatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supportchatroom',
            name='about_us_su_admin_i_25cd60_idx',
        ),
        migrations.RemoveField(
            model_name='supportchatroom',
            name='admin',
        ),
        migrations.AddField(
            model_name='supportchatroom',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins assigned to this chat room', related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last message'),
        ),
    ]
