# Generated by Django 5.2 on 2025-07-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='wallet.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.reservationday', verbose_name='روز'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['doctor', 'status'], name='reservation_doctor__5d592b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['day', 'status'], name='reservation_day_id_f285e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('day', 'doctor', 'time')},
        ),
    ]
