# Generated by Django 5.2 on 2025-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_created_at_alter_doctor_updated_at_and_more'),
        ('patients', '0014_alter_medicalrecord_created_at_and_more'),
        ('reservations', '0003_alter_reservationday_created_at_and_more'),
        ('wallet', '0004_alter_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل بیمار'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام بیمار'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='patient_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد ملی بیمار'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('available', 'آزاد'), ('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='available', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['doctor', 'status'], name='reservation_doctor__5d592b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['day', 'status'], name='reservation_day_id_f285e2_idx'),
        ),
    ]
