# Generated by Django 5.2 on 2025-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_consultation_fee_and_more'),
        ('patients', '0003_visitentry_handwritten_image'),
        ('payments', '0002_alter_paymentgateway_max_amount_and_more'),
        ('reservations', '0004_alter_reservation_amount'),
        ('wallet', '0002_alter_paymentgateway_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], default='in_person', max_length=20, verbose_name='نوع مشاوره'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('day', 'doctor', 'time', 'consultation_type')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['consultation_type', 'status'], name='reservation_consult_5c652f_idx'),
        ),
    ]
