# Generated by Django 5.2 on 2025-10-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_slug'),
        ('reservations', '0005_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_consult_5c652f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('day', 'doctor', 'time')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='consultation_type',
        ),
    ]
