# Generated by Django 5.2 on 2025-05-21 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0006_supplementary_insurance_doctor_insurance'),
        ('patients', '0011_remove_patientsfile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='doctors.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='patients.patientsfile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'درخواست چت',
                'verbose_name_plural': 'درخواست\u200cهای چت',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chatmed.chatrequest', verbose_name='درخواست مربوطه')),
            ],
            options={
                'verbose_name': 'اتاق چت',
                'verbose_name_plural': 'اتاق\u200cهای چت',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='وضعیت دسترسی')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'وضعیت دسترسی پزشک',
                'verbose_name_plural': 'وضعیت دسترسی پزشکان',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatmed.chatroom', verbose_name='اتاق چت')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
