# Generated by Django 5.2 on 2025-07-16 04:42

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_summary', models.TextField(blank=True, null=True, verbose_name='خلاصه بیماری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('finished', 'پایان یافته')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ')),
                ('patient_name', models.CharField(blank=True, max_length=100, verbose_name='نام بیمار')),
                ('patient_national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی بیمار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست چت',
                'verbose_name_plural': 'درخواست\u200cهای چت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('last_activity', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت')),
            ],
            options={
                'verbose_name': 'اتاق چت',
                'verbose_name_plural': 'اتاق\u200cهای چت',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='وضعیت دسترسی')),
                ('last_active', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
            ],
            options={
                'verbose_name': 'وضعیت دسترسی پزشک',
                'verbose_name_plural': 'وضعیت دسترسی پزشکان',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/', verbose_name='فایل')),
                ('audio', models.FileField(blank=True, null=True, upload_to='chat/audio/', verbose_name='صوت')),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('file', 'فایل'), ('audio', 'صوت')], default='text', max_length=10, verbose_name='نوع پیام')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
