# Generated by Django 5.2 on 2025-05-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='close_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل پایان چت'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان چت'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_chats', to=settings.AUTH_USER_MODEL, verbose_name='بسته شده توسط'),
        ),
    ]
