# Generated by Django 5.2 on 2025-05-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0002_chatroom_close_reason_chatroom_closed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='close_reason',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='closed_by',
        ),
    ]
