# Generated by Django 5.2 on 2025-05-23 10:36

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0003_remove_chatroom_close_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_activity',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین فعالیت'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='last_active',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین فعالیت'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال'),
        ),
    ]
