# Generated by Django 5.2 on 2025-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
