# Generated by Django 5.2 on 2025-06-05 15:47

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0005_message_audio_message_file_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('finished', 'پایان یافته')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_activity',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت'),
        ),
    ]
