# Generated by Django 5.2 on 2025-10-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0005_alter_chatrequest_amount'),
        ('payments', '0002_alter_paymentgateway_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to='payments.paymentrequest', verbose_name='درخواست پرداخت'),
        ),
    ]
