# Generated by Django 5.2 on 2025-06-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0006_alter_chatrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='disease_summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه بیماری'),
        ),
    ]
