# Generated by Django 5.2 on 2025-07-11 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmed', '0007_chatrequest_disease_summary'),
        ('wallet', '0004_alter_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام بیمار'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='patient_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد ملی بیمار'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to='wallet.transaction', verbose_name='تراکنش'),
        ),
    ]
