# Generated by Django 5.2 on 2025-07-11 13:55

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('last_active', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Chat Status',
                'verbose_name_plural': 'Admin Chat Statuses',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=65, null=True, verbose_name='اعلامیه')),
                ('published', models.BooleanField(blank=True, default=False, null=True, verbose_name='نمایش داده شود')),
            ],
            options={
                'verbose_name': 'اعلامیه',
                'verbose_name_plural': 'اعلامیه ها',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='واتساپ')),
                ('telegram', models.CharField(max_length=100, verbose_name='تلگرام')),
                ('instagram', models.CharField(max_length=100, verbose_name='اینستاگرام')),
                ('eitaa', models.CharField(max_length=100, verbose_name='ایتا')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام کاربران',
            },
        ),
        migrations.CreateModel(
            name='SupportChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Customer Support Chat', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if chat room is active')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('last_activity', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last message sent in the chat')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
