# Generated by Django 5.2 on 2025-07-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatstatus',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportchatroom',
            name='admin',
            field=models.ForeignKey(default=1, help_text='Assigned admin (default: admin with ID 1)', on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportchatroom',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer who initiated the chat (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportchatroom'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message sender; null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportchatroom',
            index=models.Index(fields=['customer', 'is_active'], name='support_sup_custome_bb6c64_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchatroom',
            index=models.Index(fields=['admin', 'is_active'], name='support_sup_admin_i_491fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='support_sup_chat_ro_edf314_idx'),
        ),
    ]
