# Generated by Django 5.2 on 2025-05-28 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminchatstatus',
            options={'verbose_name': 'وضعیت ادمین', 'verbose_name_plural': 'وضعیت\u200cهای ادمین'},
        ),
        migrations.AlterModelOptions(
            name='supportchatroom',
            options={'ordering': ['-last_activity'], 'verbose_name': 'اتاق گفت\u200cوگو', 'verbose_name_plural': 'اتاق\u200cهای گفت\u200cوگو'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='hi',
        ),
        migrations.RemoveField(
            model_name='supportchatroom',
            name='admins',
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='کاربری که چت را شروع کرده (می\u200cتواند ناشناس باشد)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='آیا این چت فعال است؟'),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='آخرین زمان فعالیت در این چت'),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='title',
            field=models.CharField(default='گفت\u200cو\u200cگوی پشتیبانی', help_text='عنوان چت', max_length=200),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='فرستنده پیام (می\u200cتواند ناشناس باشد)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
