# Generated by Django 5.2 on 2025-05-28 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_adminchatstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminchatstatus',
            options={'verbose_name': 'Admin Chat Status', 'verbose_name_plural': 'Admin Chat Statuses'},
        ),
        migrations.AlterModelOptions(
            name='supportchatroom',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='supportchatroom',
            name='admin',
            field=models.ForeignKey(default=1, help_text='Assigned admin (default: admin with ID 1)', on_delete=django.db.models.deletion.CASCADE, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer who initiated the chat (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if chat room is active'),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last message sent in the chat'),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='title',
            field=models.CharField(default='Customer Support Chat', max_length=200),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message sender; null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportchatroom',
            index=models.Index(fields=['admin', 'is_active'], name='support_sup_admin_i_491fd5_idx'),
        ),
    ]
