# Generated by Django 5.2 on 2025-05-28 19:34

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_adminchatstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchatstatus',
            name='last_active',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supportchatroom',
            name='last_activity',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last message sent in the chat'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
