# Generated by Django 5.2 on 2025-07-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms_reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sms_reminders.smsreminder', verbose_name='یادآوری'),
        ),
        migrations.AlterUniqueTogether(
            name='smsremindertemplate',
            unique_together={('name', 'reminder_type')},
        ),
        migrations.AddIndex(
            model_name='smsreminder',
            index=models.Index(fields=['scheduled_time', 'status'], name='sms_reminde_schedul_3c6dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='smsreminder',
            index=models.Index(fields=['reservation', 'reminder_type'], name='sms_reminde_reserva_cc0d61_idx'),
        ),
        migrations.AddIndex(
            model_name='smsreminder',
            index=models.Index(fields=['status', 'attempts'], name='sms_reminde_status_7febb6_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone_number', 'created_at'], name='sms_reminde_phone_n_de1436_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['success', 'created_at'], name='sms_reminde_success_cd77d7_idx'),
        ),
    ]
