# Generated by Django 5.2 on 2025-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_reminders', '0001_initial'),
    ]

    operations = [
    ]
