# Generated by Django 5.2 on 2025-05-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0008_drreportsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='homecare/icons/', verbose_name='آیکون')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پایه')),
            ],
            options={
                'verbose_name': 'خدمت در محل',
                'verbose_name_plural': 'خدمات در محل',
            },
        ),
        migrations.CreateModel(
            name='HomeCareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس محل خدمت')),
                ('requested_date', models.DateField(verbose_name='تاریخ درخواست')),
                ('requested_time', models.TimeField(verbose_name='ساعت درخواست')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات بیشتر')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('assigned', 'در حال انجام'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsfile', verbose_name='کاربر درخواست\u200cدهنده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.homecareservice', verbose_name='نوع خدمت')),
            ],
            options={
                'verbose_name': 'درخواست خدمت در محل',
                'verbose_name_plural': 'درخواست\u200cهای خدمات در محل',
                'ordering': ['-created_at'],
            },
        ),
    ]
