# Generated by Django 5.2 on 2025-07-11 11:00

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='آیکن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='هزینه حدودی (تومان)')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='نیاز به نسخه دارد؟')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='آیکن')),
            ],
            options={
                'verbose_name': 'دسته خدمات',
                'verbose_name_plural': 'دسته\u200cهای خدمات',
            },
        ),
        migrations.CreateModel(
            name='HomeCareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', django_jalali.db.models.jDateField(verbose_name='تاریخ مورد نظر')),
                ('requested_time', models.TimeField(verbose_name='ساعت مورد نظر')),
                ('address', models.TextField(verbose_name='آدرس دقیق بیمار')),
                ('extra_notes', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/', verbose_name='فایل نسخه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled_by_patient', 'لغو توسط بیمار')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.city')),
            ],
            options={
                'verbose_name': 'درخواست خدمات در محل',
                'verbose_name_plural': 'درخواست\u200cهای خدمات در محل',
            },
        ),
    ]
