# Generated by Django 5.2 on 2025-07-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('homecare', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsfile', verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_in_cities',
            field=models.ManyToManyField(related_name='homecare_services', to='doctors.city'),
        ),
        migrations.AddField(
            model_name='homecarerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homecare.service', verbose_name='خدمت درخواستی'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homecare.servicecategory'),
        ),
    ]
