# Generated by Django 5.2 on 2025-05-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0002_service_specialty_homecareservice_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecareservice',
            name='specialty',
        ),
        migrations.AddField(
            model_name='homecarerequest',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homecare.specialty'),
        ),
    ]
