# Generated by Django 5.2 on 2025-10-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_alter_service_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, verbose_name='اسلاگ'),
        ),
    ]
