# Generated by Django 5.2 on 2025-05-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_remove_homecareservice_specialty_and_more'),
        ('patients', '0008_drreportsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان دسته')),
            ],
            options={
                'verbose_name': 'دسته خدمات',
                'verbose_name_plural': 'دسته\u200cهای خدمات',
            },
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homecare.service', verbose_name='خدمت درخواستی'),
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='service',
        ),
        migrations.RemoveField(
            model_name='homecarerequest',
            name='specialty',
        ),
        migrations.AlterModelOptions(
            name='homecarerequest',
            options={'verbose_name': 'درخواست خدمات در محل', 'verbose_name_plural': 'درخواست\u200cهای خدمات در محل'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.RemoveField(
            model_name='homecarerequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='homecarerequest',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='homecarerequest',
            name='extra_notes',
            field=models.TextField(blank=True, verbose_name='توضیحات اضافی'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='هزینه حدودی (تومان)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='address',
            field=models.TextField(verbose_name='آدرس دقیق بیمار'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsfile', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_date',
            field=models.DateField(verbose_name='تاریخ مورد نظر'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_time',
            field=models.TimeField(verbose_name='ساعت مورد نظر'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام خدمت'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homecare.servicecategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomeCareService',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
