# Generated by Django 5.2 on 2025-05-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0004_servicecategory_alter_homecarerequest_service_and_more'),
        ('patients', '0008_drreportsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarerequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='extra_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsfile'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homecare.service'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecare.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
