# Generated by Django 5.2 on 2025-10-11 09:14

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0004_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarerequest',
            name='extra_notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مورد نظر'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت مورد نظر'),
        ),
    ]
