# Generated by Django 5.2 on 2025-05-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0005_alter_homecarerequest_options_alter_service_options_and_more'),
        ('patients', '0008_drreportsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarerequest',
            options={'verbose_name': 'درخواست خدمات در محل', 'verbose_name_plural': 'درخواست\u200cهای خدمات در محل'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'دسته خدمات', 'verbose_name_plural': 'دسته\u200cهای خدمات'},
        ),
        migrations.AddField(
            model_name='homecarerequest',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/', verbose_name='فایل نسخه'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='نیاز به نسخه دارد؟'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='address',
            field=models.TextField(verbose_name='آدرس دقیق بیمار'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='extra_notes',
            field=models.TextField(blank=True, verbose_name='توضیحات اضافی'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientsfile', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_date',
            field=models.DateField(verbose_name='تاریخ مورد نظر'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_time',
            field=models.TimeField(verbose_name='ساعت مورد نظر'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homecare.service', verbose_name='خدمت درخواستی'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homecare.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='هزینه حدودی (تومان)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام خدمت'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان دسته'),
        ),
    ]
