# Generated by Django 5.2 on 2025-05-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_email_tracking_number'),
        ('homecare', '0006_alter_homecarerequest_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarerequest',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='available_in_cities',
            field=models.ManyToManyField(related_name='homecare_services', to='doctors.city'),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled_by_patient', 'لغو توسط بیمار')], default='pending', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
