# Generated by Django 5.2 on 2025-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0007_homecarerequest_city_service_available_in_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='آیکن'),
        ),
    ]
