# Generated by Django 5.2 on 2025-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0008_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='آیکن'),
        ),
    ]
