# Generated by Django 5.2 on 2025-05-22 20:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0009_servicecategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarerequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homecarerequest',
            name='requested_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ مورد نظر'),
        ),
    ]
