# Generated by Django 5.1.6 on 2025-03-29 11:41

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بیمار')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('meli_code', models.CharField(blank=True, max_length=11, verbose_name='کد ملی')),
                ('involvement', models.CharField(blank=True, max_length=200, verbose_name='بیماری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پرونده بیمار',
                'verbose_name_plural': 'پرونده بیماران',
            },
        ),
        migrations.CreateModel(
            name='Reservation_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('published', models.BooleanField(default=True, verbose_name='نوبت فعال')),
            ],
            options={
                'verbose_name': 'تاریخ نوبت',
                'verbose_name_plural': 'تاریخ نوبت ها',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('time', models.TimeField(verbose_name='Time')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='turn.patients_file', verbose_name='بیمار')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='turn.reservation_day', verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
                'ordering': ('time',),
            },
        ),
    ]
