# Generated by Django 5.1.6 on 2025-04-11 19:28

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('wallet', '0004_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('published', models.BooleanField(default=True, verbose_name='نوبت فعال')),
            ],
            options={
                'verbose_name': 'تاریخ نوبت',
                'verbose_name_plural': 'تاریخ نوبت ها',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Patients_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بیمار')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('meli_code', models.CharField(blank=True, max_length=11, verbose_name='کد ملی')),
                ('involvement', models.CharField(blank=True, max_length=200, verbose_name='بیماری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرونده بیمار',
                'verbose_name_plural': 'پرونده بیماران',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت ها')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reservations', to='doctors.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reservations', to='turn.patients_file', verbose_name='بیمار')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='wallet.transaction', verbose_name='تراکنش')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='turn.reservation_day', verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
                'ordering': ('time',),
            },
        ),
    ]
