# Generated by Django 5.2 on 2025-07-16 04:42

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درگاه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد درگاه')),
                ('api_key', models.CharField(max_length=200, verbose_name='کلید API')),
                ('merchant_id', models.CharField(max_length=100, verbose_name='شناسه پذیرنده')),
                ('gateway_url', models.URLField(verbose_name='آدرس درگاه')),
                ('verify_url', models.URLField(verbose_name='آدرس تایید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10, verbose_name='حداقل مبلغ')),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('50000000'), max_digits=12, verbose_name='حداکثر مبلغ')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='درصد کمیسیون')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی در انتظار')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی مسدود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف\u200c پول\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('payment', 'پرداخت'), ('refund', 'بازگشت وجه'), ('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('commission', 'کمیسیون'), ('penalty', 'جریمه'), ('bonus', 'پاداش'), ('transfer', 'انتقال')], max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('wallet', 'کیف پول'), ('card', 'کارت بانکی'), ('cash', 'نقدی'), ('transfer', 'انتقال بانکی')], default='gateway', max_length=20, verbose_name='روش پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='کد Authority')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ کمیسیون')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='هزینه تراکنش')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ خالص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('processed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.paymentgateway', verbose_name='درگاه پرداخت')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='wallet.transaction', verbose_name='تراکنش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wallet_tran_user_id_9b1f68_idx'), models.Index(fields=['reference_id'], name='wallet_tran_referen_8e94e0_idx'), models.Index(fields=['tracking_code'], name='wallet_tran_trackin_dc2c7b_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_fb97c1_idx')],
            },
        ),
    ]
