# Generated by Django 5.2 on 2025-07-29 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='max_amount',
            field=models.IntegerField(default=50000000, verbose_name='حداکثر مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='min_amount',
            field=models.IntegerField(default=1000, verbose_name='حداقل مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ کمیسیون'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_amount',
            field=models.IntegerField(default=0, verbose_name='هزینه تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ خالص'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی مسدود'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pending_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی در انتظار'),
        ),
    ]
