# Generated by Django 5.1.6 on 2025-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_options_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('واریز', 'Deposit'), ('برداشت', 'Withdrawal'), ('purchase', 'Purchase')], max_length=20),
        ),
    ]
