# Generated by Django 5.2 on 2025-05-24 20:45

from django.db import migrations


def link_transactions_to_wallets(apps, schema_editor):
    """Link existing transactions to their corresponding wallets"""
    Transaction = apps.get_model('wallet', 'Transaction')
    Wallet = apps.get_model('wallet', 'Wallet')
    
    for transaction in Transaction.objects.all():
        try:
            wallet = Wallet.objects.get(user=transaction.user)
            transaction.wallet = wallet
            transaction.save(update_fields=['wallet'])
            print(f"Linked transaction {transaction.id} to wallet {wallet.id}")
        except Wallet.DoesNotExist:
            print(f"No wallet found for user {transaction.user.phone}")


def reverse_link_transactions(apps, schema_editor):
    """Remove wallet links from transactions"""
    Transaction = apps.get_model('wallet', 'Transaction')
    Transaction.objects.update(wallet=None)


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20250524_2043'),
    ]

    operations = [
        migrations.RunPython(link_transactions_to_wallets, reverse_link_transactions),
    ]
