# Generated by Django 5.1.6 on 2025-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('واریز', 'واریز'), ('برداشت', 'برداشت'), ('purchase', 'Purchase')], max_length=20),
        ),
    ]
