# Generated by Django 5.2 on 2025-04-27 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='MagArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='متن مقاله')),
                ('image', models.ImageField(upload_to='blog', verbose_name='تصویر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شود')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='medimag.category', verbose_name='دسته بندی')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_reply', models.BooleanField(default=False, verbose_name='آیا این یک پاسخ است؟')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('gender', models.CharField(blank=True, choices=[('M', 'آقا'), ('F', 'خانم')], default='M', max_length=1, null=True, verbose_name='جنسیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='medimag.comment', verbose_name='کامنت والد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medimag.magarticle', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
    ]
