# Generated by Django 5.2 on 2025-05-23 10:36

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='magarticle',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان'),
        ),
    ]
