# Generated by Django 5.2 on 2025-06-11 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medimag', '0002_alter_comment_date_alter_magarticle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magarticle',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='متن مقاله'),
        ),
    ]
