# Generated by Django 5.1.6 on 2025-03-05 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='متن مقاله')),
                ('image', models.ImageField(upload_to='blog', verbose_name='تصویر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شود')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
