# Generated by Django 5.1.6 on 2025-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_alter_category_options_alter_category_name_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'آقا'), ('F', 'خانم')], default='M', max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
