# Generated by Django 5.2 on 2025-05-27 19:27

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import docpages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docpages', '0002_alter_comment_created_at_alter_post_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='رنگ تگ')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لنز پزشکی',
                'verbose_name_plural': 'لنزهای پزشکی',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('none', 'بدون رسانه'), ('image', 'تصویر'), ('video', 'ویدیو')], default='none', max_length=10, verbose_name='نوع رسانه'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/', validators=[docpages.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[docpages.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='post',
            name='medical_lenses',
            field=models.ManyToManyField(blank=True, to='docpages.medicallens', verbose_name='لنزهای پزشکی'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ لایک')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='docpages.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک پست',
                'verbose_name_plural': 'لایک\u200cهای پست',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
