# Generated by Django 5.2 on 2025-07-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docpages', '0003_medicallens_remove_post_likes_post_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
