# Generated by Django 5.2 on 2025-05-22 20:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ورود'),
        ),
    ]
