# Generated by Django 5.2 on 2025-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_otp_expires_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_chat',
            field=models.BooleanField(default=False, verbose_name='اوپراتور پشتیبانی چت'),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
