# Generated by Django 5.2 on 2025-07-16 04:42

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='قالب آماده', max_length=100, null=True, verbose_name='عنوان قالب')),
                ('dr_requesting', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='پزشک درخواست کننده')),
                ('content', models.TextField(verbose_name='متن گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='VisitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ویزیت')),
                ('chief_complaint', models.TextField(verbose_name='شرح مشکل')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص')),
                ('physical_exam', models.TextField(blank=True, null=True, verbose_name='معاینه بالینی')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='طرح درمان')),
                ('prescribed_medications', models.TextField(blank=True, null=True, verbose_name='داروهای تجویزی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت تکمیلی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visit_attachments/', verbose_name='فایل پیوست')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='DrReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='doctor_templates/', verbose_name='تصویر پس\u200cزمینه')),
                ('custom_css', models.TextField(blank=True, null=True, verbose_name='استایل سفارشی')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_settings', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پرونده')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'پرونده پزشکی',
                'verbose_name_plural': 'پرونده\u200cهای پزشکی',
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بیمار')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('dr_requesting', models.CharField(blank=True, max_length=50, null=True, verbose_name='پزشک درخواست کننده')),
                ('content', models.TextField(verbose_name='شرح')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='سن بیمار')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='سابقه پزشکی')),
                ('birthdate', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'پرونده بیمار',
                'verbose_name_plural': 'پرونده\u200cهای بیماران',
            },
        ),
    ]
