# Generated by Django 5.2 on 2025-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitentry',
            name='handwritten_image',
            field=models.ImageField(blank=True, null=True, upload_to='handwritten_notes/%Y/%m/%d/', verbose_name='یادداشت دستی'),
        ),
    ]
