# Generated by Django 5.2 on 2025-05-14 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_email_tracking_number'),
        ('patients', '0002_alter_patientsfile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پرونده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='doctors.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patientsfile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'پرونده پزشکی',
                'verbose_name_plural': 'پرونده\u200cهای پزشکی',
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='VisitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ویزیت')),
                ('chief_complaint', models.TextField(verbose_name='شرح مشکل')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص')),
                ('physical_exam', models.TextField(blank=True, null=True, verbose_name='معاینه بالینی')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='طرح درمان')),
                ('prescribed_medications', models.TextField(blank=True, null=True, verbose_name='داروهای تجویزی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت تکمیلی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visit_attachments/', verbose_name='فایل پیوست')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.medicalrecord', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
            },
        ),
    ]
