# Generated by Django 5.2 on 2025-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_visitentry_handwritten_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس'),
        ),
    ]
