# Generated by Django 5.2 on 2025-05-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
