# Generated by Django 5.2 on 2025-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_medicalreport_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن بیمار'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='dr_requesting',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پزشک درخواست کننده'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام بیمار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='content',
            field=models.TextField(verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
