# Generated by Django 5.2 on 2025-05-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_email_tracking_number'),
        ('patients', '0007_medicalreport_age_medicalreport_dr_requesting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='doctor_templates/', verbose_name='تصویر پس\u200cزمینه')),
                ('custom_css', models.TextField(blank=True, null=True, verbose_name='استایل سفارشی')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_settings', to='doctors.doctor')),
            ],
        ),
    ]
