# Generated by Django 5.2 on 2025-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_drreportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsfile',
            name='name',
        ),
    ]
