# Generated by Django 5.2 on 2025-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_remove_patientsfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsfile',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
