# Generated by Django 5.2 on 2025-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientsfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsfile',
            name='name',
        ),
    ]
