# Generated by Django 5.2 on 2025-05-24 16:37

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_medicalrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پرونده'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
