# Generated by Django 5.2 on 2025-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patientsfile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsfile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
