# Generated by Django 5.2 on 2025-06-13 13:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_national_id'),
        ('patients', '0018_alter_medicalreport_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان قالب')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='doctors.doctor')),
            ],
        ),
    ]
