# Generated by Django 5.2 on 2025-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_reporttemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
