# Generated by Django 5.2 on 2025-06-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_national_id'),
        ('patients', '0020_delete_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان قالب')),
                ('dr_requesting', models.CharField(blank=True, max_length=50, null=True, verbose_name='پزشک درخواست کننده')),
                ('content', models.TextField(verbose_name='متن گزارش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='doctors.doctor')),
            ],
        ),
    ]
