# Generated by Django 5.2 on 2025-06-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='dr_requesting',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='پزشک درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='title',
            field=models.CharField(blank=True, default='قالب آماده', max_length=100, null=True, verbose_name='عنوان قالب'),
        ),
    ]
