# Generated by Django 5.1.6 on 2025-04-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, verbose_name='تخصص')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='تصویر پروفایل')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ویزیت')),
                ('is_independent', models.BooleanField(default=True, verbose_name='مستقل')),
                ('is_available', models.BooleanField(default=True, verbose_name='فعال')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس مطب')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن مطب')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.clinic', verbose_name='کلینیک')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'دوشنبه'), (1, 'سه شنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه'), (5, 'شنبه'), (6, 'یکشنبه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'زمان حضور پزشک',
                'verbose_name_plural': 'زمان های حضور پزشک',
            },
        ),
    ]
