# Generated by Django 5.2 on 2025-07-11 13:55

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='CommentTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, verbose_name='نکته')),
                ('positive', models.BooleanField(default=True, verbose_name='نکته مثبت')),
            ],
            options={
                'verbose_name': 'نکته',
                'verbose_name_plural': 'نکات',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی پزشک',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای پزشکان',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorBlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ مسدود شده')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روز مسدود شده',
                'verbose_name_plural': 'روزهای مسدود شده',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('license_number', models.CharField(max_length=50, verbose_name='شماره پروانه')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ویزیت')),
                ('consultation_duration', models.IntegerField(default=30, verbose_name='مدت زمان مشاوره (دقیقه)')),
                ('profile_image', models.ImageField(upload_to='doctor_registrations/profiles/', verbose_name='تصویر پروفایل')),
                ('license_image', models.ImageField(upload_to='doctor_registrations/licenses/', verbose_name='تصویر پروانه')),
                ('degree_image', models.ImageField(upload_to='doctor_registrations/degrees/', verbose_name='تصویر مدرک تحصیلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای ادمین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('reviewed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
            ],
            options={
                'verbose_name': 'درخواست عضویت پزشک',
                'verbose_name_plural': 'درخواست\u200cهای عضویت پزشکان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('recommendation', models.CharField(blank=True, choices=[('توصیه نمیکنم', 'توصیه نمیکنم'), ('توصیه میکنم', 'توصیه میکنم')], default=('توصیه میکنم', 'توصیه میکنم'), max_length=25, null=True, verbose_name='توصیه')),
                ('rate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('waiting_time', models.CharField(blank=True, choices=[('کمتر از نیم ساعت', 'کمتر از نیم ساعت'), ('نیم تا یک ساعت', 'نیم تا یک ساعت'), ('یک تا دو ساعت', 'یک تا دو ساعت'), ('بیش از دو ساعت', 'بیش از دو ساعت')], default=('نیم تا یک ساعت', 'نیم تا یک ساعت'), max_length=30, null=True, verbose_name='زمان انتظار')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='DrServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن نامه')),
                ('sent_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('read_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره رهگیری')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان قالب')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن نامه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب نامه',
                'verbose_name_plural': 'قالب\u200cهای نامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('appointment', 'نوبت'), ('message', 'پیام'), ('system', 'سیستم')], default='info', max_length=20, verbose_name='نوع اعلان')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک مرتبط')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_visible', models.BooleanField(default=True, verbose_name='قابل نمایش')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specializations/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplementary_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بیمه تکمیلی')),
            ],
            options={
                'verbose_name': 'بیمه تکمیلی',
                'verbose_name_plural': 'بیمه های تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پروانه')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/', verbose_name='تصویر پروفایل')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ویزیت')),
                ('consultation_duration', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='مدت زمان مشاوره (دقیقه)')),
                ('is_independent', models.BooleanField(default=False, verbose_name='مستقل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('view_count', models.PositiveIntegerField(default=93, verbose_name='تعداد بازدید')),
                ('online_visit', models.BooleanField(default=True, verbose_name='ویزیت آنلاین')),
                ('online_visit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ویزیت آنلاین')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='طول جغرافیایی')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.city', verbose_name='شهر محل خدمت')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.clinic', verbose_name='کلینیک')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['-created_at'],
            },
        ),
    ]
