# Generated by Django 5.2 on 2025-04-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_city_doctor_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
    ]
