# Generated by Django 5.2 on 2025-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=0, verbose_name='هزینه ویزیت'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='online_visit_fee',
            field=models.IntegerField(default=0, verbose_name='هزینه ویزیت آنلاین'),
        ),
        migrations.AlterField(
            model_name='doctorregistration',
            name='consultation_fee',
            field=models.IntegerField(verbose_name='هزینه ویزیت'),
        ),
    ]
