# Generated by Django 5.2 on 2025-04-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_remove_clinicspecialty_description'),
        ('doctors', '0003_alter_city_options_remove_doctor_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.clinic', verbose_name='کلینیک'),
        ),
    ]
