# Generated by Django 5.2 on 2025-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.IntegerField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
