# Generated by Django 5.2 on 2025-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_email_tracking_number_alter_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=5, unique=True, verbose_name='شماره رهگیری'),
        ),
    ]
