# Generated by Django 5.2 on 2025-05-01 06:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_drservices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('recommendation', models.CharField(blank=True, choices=[('توصیه نمیکنم', 'توصیه نمیکنم'), ('توصیه میکنم', 'توصیه میکنم')], default=('توصیه میکنم', 'توصیه میکنم'), max_length=25, null=True, verbose_name='توصیه')),
                ('rate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('checking', 'در حال بررسی'), ('confirmed', 'تایید شده')], default='checking', max_length=10, verbose_name='وضعیت')),
                ('waiting_time', models.CharField(choices=[('30min', 'کمتر از نیم ساعت'), ('1h', 'نیم تا یک ساعت'), ('2h', 'تا دو ساعت'), ('up2h', 'بیش از دو ساعت')], default=('1h', 'نیم تا یک ساعت'), max_length=30, verbose_name='زمان انتظار')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctors.doctor', verbose_name='پزشک')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('date',),
            },
        ),
    ]
