# Generated by Django 5.2 on 2025-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_email_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplementary_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بیمه تکمیلی')),
            ],
            options={
                'verbose_name': 'بیمه تکمیلی',
                'verbose_name_plural': 'بیمه های تکمیلی',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='Insurance',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.supplementary_insurance', verbose_name='بیمه های تکمیلی طرف قرارداد'),
        ),
    ]
