# Generated by Django 5.2 on 2025-05-22 20:30

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_supplementary_insurance_doctor_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='drcomment',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='email',
            name='read_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خواندن'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sent_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='email',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره رهگیری'),
        ),
    ]
