# Generated by Django 5.2 on 2025-05-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_drcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='drcomment',
            name='tips',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_tips', to='doctors.commenttips', verbose_name='نکات مثبت و منفی'),
        ),
    ]
