# Generated by Django 5.2 on 2025-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_commenttips_drcomment_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttips',
            name='positive',
            field=models.BooleanField(default=True, verbose_name='نکته مثبت'),
        ),
        migrations.AlterField(
            model_name='commenttips',
            name='tip',
            field=models.CharField(max_length=50, verbose_name='نکته'),
        ),
    ]
