# Generated by Django 5.2 on 2025-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_latitude_doctor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='online_visit',
            field=models.BooleanField(default=False, verbose_name='ویزیت آنلاین'),
        ),
    ]
