# Generated by Django 5.2 on 2025-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_commenttips_positive_alter_commenttips_tip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenttips',
            options={'verbose_name': 'نکته', 'verbose_name_plural': 'نکات'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='drcomment',
            name='waiting_time',
            field=models.CharField(choices=[('کمتر از نیم ساعت', 'کمتر از نیم ساعت'), ('نیم تا یک ساعت', 'نیم تا یک ساعت'), ('یک تا دو ساعت', 'یک تا دو ساعت'), ('بیش از دو ساعت', 'بیش از دو ساعت')], default=('نیم تا یک ساعت', 'نیم تا یک ساعت'), max_length=30, verbose_name='زمان انتظار'),
        ),
    ]
