# Generated by Django 5.2 on 2025-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_online_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='online_visit_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ویزیت آنلاین'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ویزیت'),
        ),
    ]
