# Generated by Django 5.2 on 2025-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_commenttips_options_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='view_count',
            field=models.PositiveIntegerField(default=93, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
