# Generated by Django 5.2 on 2025-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_online_visit_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='online_visit',
            field=models.BooleanField(default=True, verbose_name='ویزیت آنلاین'),
        ),
        migrations.AlterField(
            model_name='drcomment',
            name='waiting_time',
            field=models.CharField(blank=True, choices=[('کمتر از نیم ساعت', 'کمتر از نیم ساعت'), ('نیم تا یک ساعت', 'نیم تا یک ساعت'), ('یک تا دو ساعت', 'یک تا دو ساعت'), ('بیش از دو ساعت', 'بیش از دو ساعت')], default=('نیم تا یک ساعت', 'نیم تا یک ساعت'), max_length=30, null=True, verbose_name='زمان انتظار'),
        ),
    ]
