# Generated by Django 5.2 on 2025-06-06 07:23

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctor_online_visit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('license_number', models.CharField(max_length=50, verbose_name='شماره پروانه')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ویزیت')),
                ('consultation_duration', models.IntegerField(default=30, verbose_name='مدت زمان مشاوره (دقیقه)')),
                ('profile_image', models.ImageField(upload_to='doctor_registrations/profiles/', verbose_name='تصویر پروفایل')),
                ('license_image', models.ImageField(upload_to='doctor_registrations/licenses/', verbose_name='تصویر پروانه')),
                ('degree_image', models.ImageField(upload_to='doctor_registrations/degrees/', verbose_name='تصویر مدرک تحصیلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای ادمین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('reviewed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.city', verbose_name='شهر محل خدمت')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_doctor_registrations', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialization', verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'درخواست عضویت پزشک',
                'verbose_name_plural': 'درخواست\u200cهای عضویت پزشکان',
                'ordering': ['-created_at'],
            },
        ),
    ]
