# Generated by Django 5.2 on 2025-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
    ]
