# Generated by Django 5.2 on 2025-06-13 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان قالب')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن نامه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'قالب نامه',
                'verbose_name_plural': 'قالب\u200cهای نامه',
                'ordering': ['-created_at'],
            },
        ),
    ]
