# Generated by Django 5.2 on 2025-07-11 05:05

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctorblockedday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('appointment', 'نوبت'), ('message', 'پیام'), ('system', 'سیستم')], default='info', max_length=20, verbose_name='نوع اعلان')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک مرتبط')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_visible', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='doctors_not_user_id_07951f_idx'), models.Index(fields=['notification_type', 'created_at'], name='doctors_not_notific_3dfd11_idx'), models.Index(fields=['priority', 'created_at'], name='doctors_not_priorit_9bae1a_idx')],
            },
        ),
    ]
