# Generated by Django 5.2 on 2025-07-11 12:10

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ مسدود شده')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'روز مسدود شده',
                'verbose_name_plural': 'روزهای مسدود شده',
                'ordering': ['-date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
